# Generated by Django 5.0.2 on 2024-04-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folders",
            name="folder_name",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.DeleteModel(
            name="groups_folder",
        ),
    ]
